name: Publish Python Package to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Only run when a version tag like v0.0.10 is pushed

# jobs:
#   build-and-publish:
#     name: Build and Publish
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"

#       - name: Install build dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install build twine

#       - name: Build the package
#         run: python -m build

#       - name: Publish to PyPI
#         env:
#           TWINE_USERNAME: __token__
#           TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#         run: twine upload dist/*
